In [ ]:
import pandas as pd

In [2]:
df=pd.read_csv('C:\\Users\\akhil\\Desktop\\Project\\Student_performance\\Data_analaysis\\Data\\stud.csv')

In [3]:
df

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [4]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [6]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [9]:
df.shape

(1000, 8)

In [10]:
x=df.drop(["math_score"],axis=1)
y=df["math_score"]

In [11]:
from sklearn.preprocessing import LabelEncoder
#label_encoder 
le = LabelEncoder()
#onehot encoding
for column in x.columns:
    if x[column].dtype != 'object':
        x[column] = le.fit_transform(x[column])
    else:
        x = pd.get_dummies(x, columns=[column], drop_first=True)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
def evaluate_model( true,pred):
    mae = mean_absolute_error(true,pred)
    mse = mean_squared_error(true,pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(true,pred)
    return mae, mse, rmse, r2

In [14]:
import numpy as np
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

In [15]:
models={
    'Linear Regression':LinearRegression(),
    'Ridge Regression':Ridge(),
    'Lasso Regression':Lasso(),
    'KNN Regressor':KNeighborsRegressor(),
    'Decision Tree Regressor':DecisionTreeRegressor(),
    'Random Forest Regressor':RandomForestRegressor(),
    'Gradient Boosting Regressor':GradientBoostingRegressor(),
    'XGB Regressor':XGBRegressor(),
    'CatBoost Regressor': CatBoostRegressor(verbose=False),
    'AdaBoost Regressor':AdaBoostRegressor()


}



model_list = []
r2_list = []

for i in range(len(list(models))):

    model = list(models.values())[i]

    # Train model
    model.fit(x_train, y_train)

    # Make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    # Evaluate model
    train_mae, train_mse, train_rmse, train_r2 = evaluate_model(
        y_train, y_train_pred
    )

    test_mae, test_mse, test_rmse, test_r2 = evaluate_model(
        y_test, y_test_pred
    )

    # Store results
    model_list.append(list(models.keys())[i])
    r2_list.append(test_r2)

    print("Model:", list(models.keys())[i])
    print("Train R2:", train_r2)
    print("Test R2 :", test_r2)
    print("Test MAE:", test_mae)
    print("Test MSE:", test_mse)
    print("Test RMSE:", test_rmse)

Model: Linear Regression
Train R2: 0.8738280481042675
Test R2 : 0.8736182439362411
Test MAE: 4.296249997554618
Test MSE: 30.753534309745387
Test RMSE: 5.545586922025962
Model: Ridge Regression
Train R2: 0.8738184990380026
Test R2 : 0.8734977776025353
Test MAE: 4.295888222061818
Test MSE: 30.782848394643224
Test RMSE: 5.548229302637304
Model: Lasso Regression
Train R2: 0.8131240975267678
Test R2 : 0.8259783126260999
Test MAE: 5.090742287236016
Test MSE: 42.346158970865055
Test RMSE: 6.507392639979937
Model: KNN Regressor
Train R2: 0.7845416204221228
Test R2 : 0.695223606302992
Test MAE: 6.922999999999999
Test MSE: 74.16380000000001
Test RMSE: 8.611840685939331
Model: Decision Tree Regressor
Train R2: 0.9996534669718089
Test R2 : 0.7468134910067625
Test MAE: 6.18
Test MSE: 61.61
Test RMSE: 7.849203781276162
Model: Random Forest Regressor
Train R2: 0.9770614406406917
Test R2 : 0.8510473902288815
Test MAE: 4.68435238095238
Test MSE: 36.245889737528344
Test RMSE: 6.0204559410005105
Model: Gradient Boosting Regressor
Train R2: 0.902966510045648
Test R2 : 0.8733957916349769
Test MAE: 4.283020339390097
Test MSE: 30.80766549681133
Test RMSE: 5.550465340564819
Model: XGB Regressor
Train R2: 0.9951009154319763
Test R2 : 0.8209235668182373
Test MAE: 5.131189346313477
Test MSE: 43.576168060302734
Test RMSE: 6.601224739417886
Model: CatBoost Regressor
Train R2: 0.9575088961836384
Test R2 : 0.8502627518728724
Test MAE: 4.631211143921056
Test MSE: 36.43682237965824
Test RMSE: 6.036292105229687
Model: AdaBoost Regressor
Train R2: 0.8488387856513444
Test R2 : 0.853014121860932
Test MAE: 4.658910245629752
Test MSE: 35.76730840895579
Test RMSE: 5.9805775982722436

In [16]:
from sklearn.linear_model import LinearRegression

final = LinearRegression()

final_model = final.fit(x_train, y_train)

final_model

LinearRegression()

In [17]:

final_model_pred = final_model.predict(x_test)

print(final_model_pred)

[76.4844132  58.79949717 77.03684193 76.87284944 87.67605227 79.10347556
 64.47859274 52.86959592 74.22704625 48.90963826 52.8540067  41.26308779
 67.79669518 52.16852751 86.85001687 70.61807126 51.72913125 46.67096789
 48.72292899 52.65146162 73.91736029 38.7557548  57.31672586 36.04462829
 78.20710176 81.90930476 75.42104775 45.97988007 30.76773665 49.82175603
 65.84041776 70.47020832 60.30155301 83.81633768 84.46077225 45.87622499
 76.11314354 70.24954514 65.86927209 16.19502113 78.59166231 67.12931497
 68.01310929 60.33146173 79.65622264 67.64349805 72.20414575 26.15125927
 86.02825418 70.10548079 75.31317237 66.82177614 81.23746549 45.45673841
 66.16112852 67.35090062 86.28464855 58.67479346 82.15128738 81.40484132
 47.16956928 72.13777563 70.7329679  55.81430992 86.42692987 63.92318442
 59.4380607  55.77898209 57.22367569 82.23536986 71.77917783 80.62966422
 58.28467468 46.32230106 61.18309347 85.1052349  84.46081244 60.1586926
 59.32545002 53.0908955  63.62128954 40.94420952 78.92391651 66.89120372
 75.25383335 54.72449055 67.16150682 63.77389569 75.58803939 31.89460658
 73.91848813 93.94208244 62.54361931 75.43646039 29.03597708 70.72906846
 66.88730428 61.94211115 65.53426967 55.17695197 75.60133029 65.87259749
 60.7651413  58.17330279 73.65029386 68.85607769 53.28870937 79.7498503
 69.82055856 48.05242035 34.61961504 73.46159776 60.99693939 55.48174748
 76.18598191 62.21957787 49.91142348 50.29671206 72.34729423 78.59400681
 59.7241257  53.36532377 87.02953763 63.62609108 60.5874248  69.56190291
 67.69028468 66.01757847 48.70139195 72.27164227 74.12045139 76.02032821
 45.03916165 88.12977557 63.41759097 33.28351501 77.49578215 80.610479
 73.70790824 39.05276787 49.47423238 59.46813182 58.88280493 53.75324843
 77.65410088 46.72765715 43.72419649 76.55549957 57.1259292  79.19825121
 75.00559277 76.25970283 65.62254638 59.44118542 85.05467499 73.42147799
 43.58960935 62.88968594 75.92555668 51.86571978 61.99050094 64.84766828
 70.33608787 53.77628285 89.28847585 70.89105756 49.37795744 92.74349186
 60.74747554 72.12405171 83.04893798 79.14641732 80.61982947 69.87703015
 57.45550244 23.92425122 59.09035193 64.85232252 91.94071382 67.12219859
 61.40570628 59.73981378 82.059452   60.07960119 93.46861305 68.24382286
 63.110793   58.55633926 71.14560422 89.16196042 52.54465866 61.06123417
 66.95751307 65.59622356 54.06892105 43.21596653 62.07118567 67.77738607
 67.05235756 62.33647949]

In [18]:
from sklearn.metrics import r2_score

accuracy = r2_score(y_test, final_model_pred)

print("R² Score:", accuracy)
print("Accuracy:", accuracy * 100, "%")

R² Score: 0.8736182439362411
Accuracy: 87.3618243936241 %

In [19]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

print("R² Score:", r2_score(y_test, final_model_pred))
print("MAE:", mean_absolute_error(y_test, final_model_pred))
print("MSE:", mean_squared_error(y_test, final_model_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, final_model_pred)))

R² Score: 0.8736182439362411
MAE: 4.296249997554618
MSE: 30.753534309745387
RMSE: 5.545586922025962

In [21]:
df.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')